export const skill = [
    { name: 'JavaScript', percent: 75 },
    { name: 'React', percent: 80 },
    { name: 'NodeJS', percent: 65 },
    { name: 'ExpressJS', percent: 75 },
    { name: 'MongoDB', percent: 80 },
    { name: 'HTML', percent: 95 },
    { name: 'CSS', percent: 85 },
    { name: 'Redux', percent: 65 },
    { name: 'Firebase', percent: 60 },
    { name: 'Git', percent: 75 },
    { name: 'VS Code', percent: 75 },
    { name: 'Heroku', percent: 60 },
    { name: 'NPM', percent: 70 },
    { name: 'Chrome Dev Tool', percent: 75 },
    { name: 'Material-UI', percent: 65 },
];